// <copyright file="CitizenTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class CitizenTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CitizenTest))]
public void Constructor438()
{
    Citizen citizen;
    citizen = this.Constructor(0, (string)null);
    Assert.IsNotNull((object)citizen);
    Assert.AreEqual<bool>(false, citizen.EligibleToVote);
    Assert.IsNull(citizen.VotingPlace);
    Assert.AreEqual<bool>(false, citizen.HasVoted);
    Assert.AreEqual<string>((string)null, ((Person)citizen).Cpr);
    Assert.AreEqual<string>((string)null, ((Person)citizen).PassportNumber);
    Assert.AreEqual<string>("", ((Person)citizen).Name);
    Assert.AreEqual<string>("", ((Person)citizen).Address);
    Assert.AreEqual<string>("", ((Person)citizen).PlaceOfBirth);
    Assert.AreEqual<int>(0, ((Person)citizen).DbId);
}
    }
}
