// <copyright file="CitizenTest.SetHasVoted.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using DigitalVoterList.Utilities;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class CitizenTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CitizenTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void SetHasVoted01()
{
    HashSet<VoterCard> hashSet;
    Citizen citizen;
    VoterCard[] voterCards = new VoterCard[14592];
    hashSet = new HashSet<VoterCard>((IEnumerable<VoterCard>)voterCards);
    citizen = new Citizen(0, (string)null);
    citizen.EligibleToVote = false;
    citizen.VotingPlace = (VotingVenue)null;
    citizen.VoterCards = hashSet;
    citizen.SecurityQuestions = (HashSet<Quiz>)null;
    ((Person)citizen).PassportNumber = (string)null;
    citizen.SetHasVoted();
    this.SetHasVoted(citizen);
}
    }
}
