// <copyright file="CitizenTest.VoterCardsGet.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using DigitalVoterList.Utilities;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class CitizenTest
    {
[TestMethod]
[PexGeneratedBy(typeof(CitizenTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void VoterCardsGet04()
{
    HashSet<Quiz> hashSet;
    Citizen citizen;
    HashSet<VoterCard> hashSet1_;
    Quiz[] quizs = new Quiz[14592];
    Quiz s0 = new Quiz((string)null, (string)null);
    quizs[1] = s0;
    quizs[2] = s0;
    quizs[3] = s0;
    hashSet = new HashSet<Quiz>((IEnumerable<Quiz>)quizs);
    citizen = new Citizen(0, (string)null);
    citizen.EligibleToVote = false;
    citizen.VotingPlace = (VotingVenue)null;
    citizen.VoterCards = (HashSet<VoterCard>)null;
    citizen.SecurityQuestions = hashSet;
    ((Person)citizen).PassportNumber = (string)null;
    citizen.SetHasVoted();
    hashSet1_ = this.VoterCardsGet(citizen);
}
[TestMethod]
[PexGeneratedBy(typeof(CitizenTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void VoterCardsGet03()
{
    HashSet<Quiz> hashSet;
    Citizen citizen;
    HashSet<VoterCard> hashSet1_;
    Quiz[] quizs = new Quiz[14848];
    Quiz s0 = new Quiz((string)null, (string)null);
    quizs[0] = s0;
    quizs[1] = s0;
    hashSet = new HashSet<Quiz>((IEnumerable<Quiz>)quizs);
    citizen = new Citizen(0, (string)null);
    citizen.EligibleToVote = false;
    citizen.VotingPlace = (VotingVenue)null;
    citizen.VoterCards = (HashSet<VoterCard>)null;
    citizen.SecurityQuestions = hashSet;
    ((Person)citizen).PassportNumber = (string)null;
    citizen.SetHasVoted();
    hashSet1_ = this.VoterCardsGet(citizen);
}
[TestMethod]
[PexGeneratedBy(typeof(CitizenTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void VoterCardsGet02()
{
    HashSet<Quiz> hashSet;
    Citizen citizen;
    HashSet<VoterCard> hashSet1_;
    Quiz[] quizs = new Quiz[15360];
    Quiz s0 = new Quiz((string)null, (string)null);
    quizs[0] = s0;
    hashSet = new HashSet<Quiz>((IEnumerable<Quiz>)quizs);
    citizen = new Citizen(0, (string)null);
    citizen.EligibleToVote = false;
    citizen.VotingPlace = (VotingVenue)null;
    citizen.VoterCards = (HashSet<VoterCard>)null;
    citizen.SecurityQuestions = hashSet;
    ((Person)citizen).PassportNumber = (string)null;
    citizen.SetHasVoted();
    hashSet1_ = this.VoterCardsGet(citizen);
}
[TestMethod]
[PexGeneratedBy(typeof(CitizenTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void VoterCardsGet01()
{
    HashSet<Quiz> hashSet;
    Citizen citizen;
    HashSet<VoterCard> hashSet1_;
    Quiz[] quizs = new Quiz[14596];
    hashSet = new HashSet<Quiz>((IEnumerable<Quiz>)quizs);
    citizen = new Citizen(0, (string)null);
    citizen.EligibleToVote = false;
    citizen.VotingPlace = (VotingVenue)null;
    citizen.VoterCards = (HashSet<VoterCard>)null;
    citizen.SecurityQuestions = hashSet;
    ((Person)citizen).PassportNumber = (string)null;
    citizen.SetHasVoted();
    hashSet1_ = this.VoterCardsGet(citizen);
}
    }
}
