// <copyright file="ContentControllerTest.HasPermissionToUse.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using DigitalVoterList.Election;
using System.Windows.Controls;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Controllers
{
    public partial class ContentControllerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ContentControllerTest))]
public void HasPermissionToUse840()
{
    ContentController contentController;
    User user;
    bool b;
    contentController = new ContentController();
    contentController.View = (UserControl)null;
    user = new User(0);
    user.Username = (string)null;
    user.UserSalt = (string)null;
    user.Valid = false;
    user.Title = (string)null;
    ((Person)user).Cpr = (string)null;
    ((Person)user).PassportNumber = (string)null;
    b = this.HasPermissionToUse(contentController, user);
    Assert.AreEqual<bool>(true, b);
    Assert.IsNotNull((object)contentController);
    Assert.IsNull(contentController.View);
}
[TestMethod]
[PexGeneratedBy(typeof(ContentControllerTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void HasPermissionToUseThrowsNullReferenceException160()
{
    ContentController contentController;
    bool b;
    contentController = new ContentController();
    contentController.View = (UserControl)null;
    b = this.HasPermissionToUse(contentController, (User)null);
}
    }
}
