// <copyright file="DAOFactoryTest.getDAO.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class DAOFactoryTest
    {
[TestMethod]
[PexGeneratedBy(typeof(DAOFactoryTest))]
public void getDAO278()
{
    User user;
    IDataAccessObject iDataAccessObject;
    user = new User(0);
    user.Username = (string)null;
    user.UserSalt = (string)null;
    user.Valid = false;
    user.Title = (string)null;
    ((Person)user).Cpr = (string)null;
    ((Person)user).PassportNumber = (string)null;
    iDataAccessObject = this.getDAO(user);
    Assert.IsNotNull((object)iDataAccessObject);
}
[TestMethod]
[PexGeneratedBy(typeof(DAOFactoryTest))]
[PexRaisedException(typeof(ArgumentNullException))]
public void getDAOThrowsArgumentNullException445()
{
    IDataAccessObject iDataAccessObject;
    iDataAccessObject = this.getDAO((User)null);
}
    }
}
