// <copyright file="DAOPermissionProxyTest.GetPermissions.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class DAOPermissionProxyTest
    {
[TestMethod]
[PexGeneratedBy(typeof(DAOPermissionProxyTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void GetPermissionsThrowsNullReferenceException480()
{
    DAOPermissionProxy dAOPermissionProxy;
    HashSet<SystemAction> hashSet;
    dAOPermissionProxy = new DAOPermissionProxy((User)null, (IDataAccessObject)null);
    hashSet = this.GetPermissions(dAOPermissionProxy, (User)null);
}
    }
}
