// <copyright file="DAOPermissionProxyTest.Find01.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using System.Collections.Generic;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class DAOPermissionProxyTest
    {
[TestMethod]
[PexGeneratedBy(typeof(DAOPermissionProxyTest))]
[PexRaisedException(typeof(PermissionException))]
public void Find01ThrowsPermissionException769()
{
    User user;
    DAOPermissionProxy dAOPermissionProxy;
    List<User> list;
    user = new User(0);
    user.Username = (string)null;
    user.UserSalt = (string)null;
    user.Valid = false;
    user.Title = (string)null;
    ((Person)user).Cpr = (string)null;
    ((Person)user).PassportNumber = (string)null;
    dAOPermissionProxy = new DAOPermissionProxy(user, (IDataAccessObject)null);
    list = this.Find01(dAOPermissionProxy, (User)null);
}
[TestMethod]
[PexGeneratedBy(typeof(DAOPermissionProxyTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void Find01ThrowsNullReferenceException478()
{
    DAOPermissionProxy dAOPermissionProxy;
    List<User> list;
    dAOPermissionProxy = new DAOPermissionProxy((User)null, (IDataAccessObject)null);
    list = this.Find01(dAOPermissionProxy, (User)null);
}
[TestMethod]
[PexGeneratedBy(typeof(DAOPermissionProxyTest))]
[PexRaisedException(typeof(PermissionException))]
public void FindThrowsPermissionException28()
{
    User user;
    DAOPermissionProxy dAOPermissionProxy;
    List<Person> list;
    user = new User(0);
    user.Username = (string)null;
    user.UserSalt = (string)null;
    user.Valid = false;
    user.Title = (string)null;
    ((Person)user).Cpr = (string)null;
    ((Person)user).PassportNumber = (string)null;
    dAOPermissionProxy = new DAOPermissionProxy(user, (IDataAccessObject)null);
    list = this.Find(dAOPermissionProxy, (Person)null);
}
[TestMethod]
[PexGeneratedBy(typeof(DAOPermissionProxyTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void FindThrowsNullReferenceException64()
{
    DAOPermissionProxy dAOPermissionProxy;
    List<Person> list;
    dAOPermissionProxy = new DAOPermissionProxy((User)null, (IDataAccessObject)null);
    list = this.Find(dAOPermissionProxy, (Person)null);
}
    }
}
