// <copyright file="DAOPermissionProxyTest.LoadUser02.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class DAOPermissionProxyTest
    {
[TestMethod]
[PexGeneratedBy(typeof(DAOPermissionProxyTest))]
[PexRaisedException(typeof(NullReferenceException))]
public void LoadUser02ThrowsNullReferenceException927()
{
    DAOPermissionProxy dAOPermissionProxy;
    User user;
    dAOPermissionProxy = new DAOPermissionProxy((User)null, (IDataAccessObject)null);
    user = this.LoadUser02(dAOPermissionProxy, 0);
}
    }
}
