// <copyright file="ElectionEventTest.VotingVenueForCitizen.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class ElectionEventTest
    {
[TestMethod]
[PexGeneratedBy(typeof(ElectionEventTest))]
[PexRaisedException(typeof(PermissionException))]
public void VotingVenueForCitizenThrowsPermissionException630()
{
    VotingVenue votingVenue;
    ElectionEvent s0 = new ElectionEvent(default(DateTime), (string)null);
    votingVenue = this.VotingVenueForCitizen(s0, (Citizen)null);
}
    }
}
