// <copyright file="LoginEventArgsTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Views
{
    public partial class LoginEventArgsTest
    {
[TestMethod]
[PexGeneratedBy(typeof(LoginEventArgsTest))]
public void Constructor702()
{
    LoginEventArgs loginEventArgs;
    loginEventArgs = this.Constructor((string)null, (string)null);
    Assert.IsNotNull((object)loginEventArgs);
    Assert.AreEqual<string>((string)null, loginEventArgs.Password);
    Assert.AreEqual<string>((string)null, loginEventArgs.Username);
}
    }
}
