// <copyright file="PermissionExceptionTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class PermissionExceptionTest
    {
[TestMethod]
[PexGeneratedBy(typeof(PermissionExceptionTest))]
public void Constructor442()
{
    PermissionException permissionException;
    permissionException =
      this.Constructor(SystemAction.Nothing, (User)null, (string)null);
    Assert.IsNotNull((object)permissionException);
    Assert.AreEqual<SystemAction>
        (SystemAction.Nothing, permissionException.SystemAction);
    Assert.IsNull(permissionException.User);
    Assert.IsNull(((Exception)permissionException).InnerException);
}
    }
}
