// <copyright file="QuizTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Utilities
{
    public partial class QuizTest
    {
[TestMethod]
[PexGeneratedBy(typeof(QuizTest))]
public void Constructor628()
{
    Quiz quiz;
    quiz = this.Constructor((string)null, (string)null);
    Assert.IsNotNull((object)quiz);
    Assert.AreEqual<string>((string)null, quiz.Question);
    Assert.AreEqual<string>((string)null, quiz.Answer);
}
    }
}
