// <copyright file="RandomQuestionControllerTest.RequestQuestion.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using DigitalVoterList.Election;
using System.Collections.Generic;
using DigitalVoterList.Utilities;
using DigitalVoterList.Views;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Controllers
{
    public partial class RandomQuestionControllerTest
    {
[TestMethod]
[PexGeneratedBy(typeof(RandomQuestionControllerTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void RequestQuestion01()
{
    HashSet<VoterCard> hashSet;
    Citizen citizen;
    RandomQuestionController randomQuestionController;
    VoterCard[] voterCards = new VoterCard[15360];
    hashSet = new HashSet<VoterCard>((IEnumerable<VoterCard>)voterCards);
    citizen = new Citizen(0, (string)null);
    citizen.EligibleToVote = false;
    citizen.VotingPlace = (VotingVenue)null;
    citizen.VoterCards = hashSet;
    citizen.SecurityQuestions = (HashSet<Quiz>)null;
    ((Person)citizen).PassportNumber = (string)null;
    citizen.SetHasVoted();
    randomQuestionController =
      new RandomQuestionController((SecurityQuesitonView)null, citizen);
    this.RequestQuestion(randomQuestionController, (object)null, (EventArgs)null);
}
    }
}
