// <copyright file="SystemActionsTest.getSystemAction.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using DigitalVoterList.Election;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

public partial class SystemActionsTest
{
[TestMethod]
[PexGeneratedBy(typeof(global::SystemActionsTest))]
public void getSystemAction340()
{
    SystemAction i;
    i = this.getSystemAction((string)null);
    Assert.AreEqual<SystemAction>(SystemAction.Nothing, i);
}
}
