// <copyright file="UserTest.FetchPermissions.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.Pex.Framework.Generated;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace DigitalVoterList.Election
{
    public partial class UserTest
    {
[TestMethod]
[PexGeneratedBy(typeof(UserTest))]
[Ignore]
[PexDescription("the test state was: path bounds exceeded")]
public void FetchPermissions809()
{
    using (PexTraceListenerContext.Create())
    {
      User user;
      bool b;
      user = new User(0);
      user.Username = (string)null;
      user.UserSalt = (string)null;
      user.Valid = false;
      user.Title = (string)null;
      ((Person)user).Cpr = (string)null;
      ((Person)user).PassportNumber = (string)null;
      b = this.FetchPermissions(user, (string)null, (string)null);
    }
}
    }
}
