// <copyright file="VoterCardTest.Constructor.g.cs">Copyright ©  2011</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace DigitalVoterList.Election
{
    public partial class VoterCardTest
    {
[TestMethod]
[PexGeneratedBy(typeof(VoterCardTest))]
public void Constructor101()
{
    VoterCard voterCard;
    voterCard = this.Constructor((ElectionEvent)null, (Citizen)null);
    Assert.IsNotNull((object)voterCard);
    Assert.IsNull(voterCard.ElectionEvent);
    Assert.IsNull(voterCard.Citizen);
    Assert.AreEqual<int>(0, voterCard.Id);
    Assert.AreEqual<string>((string)null, voterCard.IdKey);
    Assert.AreEqual<bool>(true, voterCard.Valid);
}
    }
}
